version: "3"

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=uuser
      - APP_DB_PASS=ppassword
      - APP_DB_NAME=uchicollab
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  server:
    build: .
    restart: always
    environment:
      - DB_HOST=postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres

  ui:
    build: ./ui
    restart: always
    environment:
      - NODE_ENV=sberprod
    ports:
      - 80:80
    links:
      - server
    depends_on:
      - server