export const Subjects = [
    { value: 'algebra', label: 'Алгебра' },
    { value: 'geometry', label: 'Геометрия' },
    { value: 'russian', label: 'Русский язык' },
    { value: 'english', label: 'Английский язык' },
    { value: 'biology', label: 'Биология' },
    { value: 'informatics', label: 'Информатика' },
    { value: 'socialstudies', label: 'Обществознание' },
    { value: 'physics', label: 'Физика' },
    { value: 'chemestry', label: 'Химия' },
    { value: 'naturalscience', label: 'Естествознание' },
    { value: 'economics', label: 'Экономика' },
    { value: 'jurisprudence', label: 'Правоведение' },
    { value: 'philosophy', label: 'Философия' },
    { value: 'ecology', label: 'Экология' },
    { value: 'astronomy', label: 'Астрономия' },
];

export const SubjectColor = {
    algebra: "rgb(189, 187, 240)",
    geometry: "rgb(171, 225, 250)",
    russian: "rgb(245, 190, 178)",
    english: "rgb(251, 240, 153)",
    biology: "rgb(206, 242, 201)",
    informatics: "rgb(243, 191, 159)",
    socialstudies: "rgb(250, 223, 202)",
    physics: "rgb(178, 186, 202)",
    naturalscience: "rgb(213, 219, 227)",
    economics: "rgb(245, 231, 208)",
    jurisprudence: "rgb(248, 213, 224)",
    philosophy: "rgb(232, 224, 208)",
    ecology: "rgb(170, 231, 187)",
    astronomy: "rgb(250, 228, 222)",
    chemestry: "#fbe4ff",
};